# -*- mode: ruby -*-
# vi: set ft=ruby :

defaultbox = "ubuntu/trusty64"
box = ENV['BOX'] || defaultbox

ENV['ANSIBLE_ROLES_PATH'] = "../../"

Vagrant.configure(2) do |config|

  config.vm.box = box

  config.vm.define "postgres_14_04_9_4" do |postgres_14_04_9_4_cfg|
    postgres_14_04_9_4_cfg.vm.box = "ubuntu/trusty64"
    postgres_14_04_9_4_cfg.vm.hostname = "postgres.14.04.9.4"
    postgres_14_04_9_4_cfg.vm.network "private_network", type: "dhcp"
    postgres_14_04_9_4_cfg.vm.provider :virtualbox do |v|
      v.name = "postgres.14.04.9.4"
    end
  end

  config.vm.define "postgres_14_04_9_3" do |postgres_14_04_9_3_cfg|
    postgres_14_04_9_3_cfg.vm.box = "ubuntu/trusty64"
    postgres_14_04_9_3_cfg.vm.hostname = "postgres.14.04.9.3"
    postgres_14_04_9_3_cfg.vm.network "private_network", type: "dhcp"
    postgres_14_04_9_3_cfg.vm.provider :virtualbox do |v|
      v.name = "postgres.14.04.9.3"
    end
  end

  config.vm.define "postgres_12_04_9_4" do |postgres_12_04_9_4_cfg|
    postgres_12_04_9_4_cfg.vm.box = "ubuntu/precise64"
    postgres_12_04_9_4_cfg.vm.hostname = "postgres.12.04.9.4"
    postgres_12_04_9_4_cfg.vm.network "private_network", type: "dhcp"
    postgres_12_04_9_4_cfg.vm.provider :virtualbox do |v|
      v.name = "postgres.12.04.9.4"
    end
  end

  config.vm.define "postgres_12_04_9_3" do |postgres_12_04_9_3_cfg|
    postgres_12_04_9_3_cfg.vm.box = "ubuntu/precise64"
    postgres_12_04_9_3_cfg.vm.hostname = "postgres.12.04.9.3"
    postgres_12_04_9_3_cfg.vm.network "private_network", type: "dhcp"
    postgres_12_04_9_3_cfg.vm.provider :virtualbox do |v|
      v.name = "postgres.12.04.9.3"
    end
  end

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "vagrant.yml"
    ansible.sudo = true
    # ansible.tags = ['debug']
    ansible.groups = {
      "vagrant" => ["postgres_14_04_9_4", "postgres_14_04_9_3", "postgres_12_04_9_3", "postgres_12_04_9_4"],
    }
    ansible.extra_vars = {
      ansible_ssh_user: 'vagrant',
      hbase_standalone:   true,
    }

  end

end
